// export const PackagesData = [
//   {
//     id: "1",
//     journeyDays: "7",
//     price: "750",
//     packageimage: "/morocco/package.jpg",
//     daysImages: [],
//     key: "package1",
//     review: "8.5",
//     expertJudgement: "9",
//   },
//   {
//     id: "2",
//     price: "600",
//     journeyDays: "5",
//     packageimage: "/algeria/package.jpg",
//     daysImages: [],
//     key: "package2",
//     review: "7.81",
//     expertJudgement: "8.11",
//   },
//   {
//     id: "3",
//     price: "950",
//     journeyDays: "7",
//     packageimage: "/egypt/package.jpg",
//     daysImages: [],
//     key: "package3",
//     review: "9.22",
//     expertJudgement: "9.52",
//   },
//   {
//     id: "4",
//     price: "850",
//     journeyDays: "6",
//     packageimage: "/riyad/package.jpg",
//     daysImages: [],
//     key: "package4",
//     review: "8.73",
//     expertJudgement: "9.03",
//   },
//   {
//     id: "5",
//     price: "1200",
//     journeyDays: "5",
//     packageimage: "/emirates/package.jpg",
//     daysImages: [],
//     key: "package5",
//     review: "8.54",
//     expertJudgement: "10.00",
//   },
//   {
//     id: "6",
//     price: "900",
//     journeyDays: "5",
//     packageimage: "/gatar/package.jpg",
//     daysImages: [],
//     key: "package6",
//     review: "8.95",
//     expertJudgement: "9.25",
//   },
//   {
//     id: "7",
//     price: "850",
//     journeyDays: "6",
//     packageimage: "/oman/package.jpg",
//     daysImages: [],
//     key: "package7",
//     review: "9.06",
//     expertJudgement: "9.26",
//   },
//   {
//     id: "8",
//     price: "950",
//     journeyDays: "7",
//     packageimage: "/turkey/package.jpg",
//     daysImages: [],
//     key: "package8",
//     review: "9.37",
//     expertJudgement: "9.57",
//   },
//   {
//     id: "9",
//     price: "800",
//     journeyDays: "6",
//     packageimage: "/iran/package.jpg",
//     daysImages: [],
//     key: "package9",
//     review: "8.78",
//     expertJudgement: "9.08",
//   },
//   {
//     id: "10",
//     price: "1100",
//     journeyDays: "7",
//     packageimage: "/indonisia/package.jpg",
//     daysImages: [],
//     key: "package10",
//     review: "8.59",
//     expertJudgement: "10.00",
//   },
//   {
//     id: "11",
//     price: "900",
//     journeyDays: "6",
//     packageimage: "/malysia/package.jpg",
//     daysImages: [],
//     key: "package11",
//     review: "9.00",
//     expertJudgement: "9.30",
//   },
//   {
//     id: "12",
//     price: "1200",
//     journeyDays: "7",
//     packageimage: "/umrah/package.jpg",
//     daysImages: [],
//     key: "package12",
//     review: "8.81",
//     expertJudgement: "10.00",
//   },
//   {
//     id: "13",
//     price: "2500",
//     journeyDays: "10",
//     packageimage: "/hadj/package.jpg",
//     daysImages: [],
//     key: "package13",
//     review: "09.00",
//     expertJudgement: "10.00",
//   },
//   {
//     id: "14",
//     price: "950",
//     journeyDays: "6",
//     packageimage: "/petra/package.jpg",
//     daysImages: [],
//     key: "package14",
//     expertJudgement: "9.52",
//     review: "9.22",
//   },
// ];
